server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
      - id: micro1
        uri: http://localhost:8085
        predicates: 
        - Path=/micro1/**
      - id: micro2
        uri: http://localhost:8086
        predicates: 
        - Path=/micro2/**